const fetch = require('node-fetch');
const safeEval = require('safe-eval');

const pages = [
  'https://socialblade.com/youtube/top/category/autos/mostsubscribed',
  'https://socialblade.com/youtube/top/category/autos/mostsubscribed',
  'https://socialblade.com/youtube/top/category/comedy/mostsubscribed',
  'https://socialblade.com/youtube/top/category/education/mostsubscribed',
  'https://socialblade.com/youtube/top/category/entertainment/mostsubscribed',
  'https://socialblade.com/youtube/top/category/film/mostsubscribed',
  'https://socialblade.com/youtube/top/category/games/mostsubscribed',
  'https://socialblade.com/youtube/top/category/tech/mostsubscribed',
  'https://socialblade.com/youtube/top/category/shows/mostsubscribed',
  'https://socialblade.com/youtube/top/country/au',
  'https://socialblade.com/youtube/top/country/ca',
  'https://socialblade.com/youtube/top/country/gb',
  'https://socialblade.com/youtube/top/country/us',
  'https://socialblade.com/youtube/top/country/af',
  'https://socialblade.com/youtube/top/country/al',
  'https://socialblade.com/youtube/top/country/dz',
  'https://socialblade.com/youtube/top/country/as',
  'https://socialblade.com/youtube/top/country/ad',
  'https://socialblade.com/youtube/top/country/ao',
  'https://socialblade.com/youtube/top/country/ai',
  'https://socialblade.com/youtube/top/country/ag',
  'https://socialblade.com/youtube/top/country/ar',
  'https://socialblade.com/youtube/top/country/am',
  'https://socialblade.com/youtube/top/country/aw',
  'https://socialblade.com/youtube/top/country/au',
  'https://socialblade.com/youtube/top/country/at',
  'https://socialblade.com/youtube/top/country/az',
  'https://socialblade.com/youtube/top/country/bs',
  'https://socialblade.com/youtube/top/country/bh',
  'https://socialblade.com/youtube/top/country/bd',
  'https://socialblade.com/youtube/top/country/bb',
  'https://socialblade.com/youtube/top/country/by',
  'https://socialblade.com/youtube/top/country/be',
  'https://socialblade.com/youtube/top/country/bz',
  'https://socialblade.com/youtube/top/country/bj',
  'https://socialblade.com/youtube/top/country/bm',
  'https://socialblade.com/youtube/top/country/bt',
  'https://socialblade.com/youtube/top/country/bo',
  'https://socialblade.com/youtube/top/country/bl',
  'https://socialblade.com/youtube/top/country/ba',
  'https://socialblade.com/youtube/top/country/bw',
  'https://socialblade.com/youtube/top/country/br',
  'https://socialblade.com/youtube/top/country/bc',
  'https://socialblade.com/youtube/top/country/bn',
  'https://socialblade.com/youtube/top/country/bg',
  'https://socialblade.com/youtube/top/country/bf',
  'https://socialblade.com/youtube/top/country/bi',
  'https://socialblade.com/youtube/top/country/kh',
  'https://socialblade.com/youtube/top/country/cm',
  'https://socialblade.com/youtube/top/country/ca',
  'https://socialblade.com/youtube/top/country/ic',
  'https://socialblade.com/youtube/top/country/cv',
  'https://socialblade.com/youtube/top/country/ky',
  'https://socialblade.com/youtube/top/country/cf',
  'https://socialblade.com/youtube/top/country/td',
  'https://socialblade.com/youtube/top/country/cd',
  'https://socialblade.com/youtube/top/country/cl',
  'https://socialblade.com/youtube/top/country/cn',
  'https://socialblade.com/youtube/top/country/ci',
  'https://socialblade.com/youtube/top/country/cs',
  'https://socialblade.com/youtube/top/country/co',
  'https://socialblade.com/youtube/top/country/cc',
  'https://socialblade.com/youtube/top/country/cg',
  'https://socialblade.com/youtube/top/country/ck',
  'https://socialblade.com/youtube/top/country/cr',
  'https://socialblade.com/youtube/top/country/ct',
  'https://socialblade.com/youtube/top/country/hr',
  'https://socialblade.com/youtube/top/country/cu',
  'https://socialblade.com/youtube/top/country/cb',
  'https://socialblade.com/youtube/top/country/cy',
  'https://socialblade.com/youtube/top/country/cz',
  'https://socialblade.com/youtube/top/country/dk',
  'https://socialblade.com/youtube/top/country/dj',
  'https://socialblade.com/youtube/top/country/dm',
  'https://socialblade.com/youtube/top/country/do',
  'https://socialblade.com/youtube/top/country/tm',
  'https://socialblade.com/youtube/top/country/ec',
  'https://socialblade.com/youtube/top/country/eg',
  'https://socialblade.com/youtube/top/country/sv',
  'https://socialblade.com/youtube/top/country/gq',
  'https://socialblade.com/youtube/top/country/er',
  'https://socialblade.com/youtube/top/country/ee',
  'https://socialblade.com/youtube/top/country/et',
  'https://socialblade.com/youtube/top/country/fa',
  'https://socialblade.com/youtube/top/country/fo',
  'https://socialblade.com/youtube/top/country/fj',
  'https://socialblade.com/youtube/top/country/fi',
  'https://socialblade.com/youtube/top/country/fr',
  'https://socialblade.com/youtube/top/country/gf',
  'https://socialblade.com/youtube/top/country/pf',
  'https://socialblade.com/youtube/top/country/fs',
  'https://socialblade.com/youtube/top/country/ga',
  'https://socialblade.com/youtube/top/country/gm',
  'https://socialblade.com/youtube/top/country/ge',
  'https://socialblade.com/youtube/top/country/de',
  'https://socialblade.com/youtube/top/country/gh',
  'https://socialblade.com/youtube/top/country/gi',
  'https://socialblade.com/youtube/top/country/gb',
  'https://socialblade.com/youtube/top/country/gr',
  'https://socialblade.com/youtube/top/country/gl',
  'https://socialblade.com/youtube/top/country/gd',
  'https://socialblade.com/youtube/top/country/gp',
  'https://socialblade.com/youtube/top/country/gu',
  'https://socialblade.com/youtube/top/country/gt',
  'https://socialblade.com/youtube/top/country/gn',
  'https://socialblade.com/youtube/top/country/gy',
  'https://socialblade.com/youtube/top/country/ht',
  'https://socialblade.com/youtube/top/country/hw',
  'https://socialblade.com/youtube/top/country/hn',
  'https://socialblade.com/youtube/top/country/hk',
  'https://socialblade.com/youtube/top/country/hu',
  'https://socialblade.com/youtube/top/country/is',
  'https://socialblade.com/youtube/top/country/in',
  'https://socialblade.com/youtube/top/country/id',
  'https://socialblade.com/youtube/top/country/ir',
  'https://socialblade.com/youtube/top/country/iq',
  'https://socialblade.com/youtube/top/country/ie',
  'https://socialblade.com/youtube/top/country/im',
  'https://socialblade.com/youtube/top/country/il',
  'https://socialblade.com/youtube/top/country/it',
  'https://socialblade.com/youtube/top/country/jm',
  'https://socialblade.com/youtube/top/country/jp',
  'https://socialblade.com/youtube/top/country/jo',
  'https://socialblade.com/youtube/top/country/kz',
  'https://socialblade.com/youtube/top/country/ke',
  'https://socialblade.com/youtube/top/country/ki',
  'https://socialblade.com/youtube/top/country/kp',
  'https://socialblade.com/youtube/top/country/kr',
  'https://socialblade.com/youtube/top/country/kw',
  'https://socialblade.com/youtube/top/country/kg',
  'https://socialblade.com/youtube/top/country/la',
  'https://socialblade.com/youtube/top/country/lv',
  'https://socialblade.com/youtube/top/country/lb',
  'https://socialblade.com/youtube/top/country/ls',
  'https://socialblade.com/youtube/top/country/lr',
  'https://socialblade.com/youtube/top/country/ly',
  'https://socialblade.com/youtube/top/country/li',
  'https://socialblade.com/youtube/top/country/lt',
  'https://socialblade.com/youtube/top/country/lu',
  'https://socialblade.com/youtube/top/country/mo',
  'https://socialblade.com/youtube/top/country/mk',
  'https://socialblade.com/youtube/top/country/mg',
  'https://socialblade.com/youtube/top/country/my',
  'https://socialblade.com/youtube/top/country/mw',
  'https://socialblade.com/youtube/top/country/mv',
  'https://socialblade.com/youtube/top/country/ml',
  'https://socialblade.com/youtube/top/country/mt',
  'https://socialblade.com/youtube/top/country/mh',
  'https://socialblade.com/youtube/top/country/mq',
  'https://socialblade.com/youtube/top/country/mr',
  'https://socialblade.com/youtube/top/country/mu',
  'https://socialblade.com/youtube/top/country/me',
  'https://socialblade.com/youtube/top/country/mx',
  'https://socialblade.com/youtube/top/country/mi',
  'https://socialblade.com/youtube/top/country/md',
  'https://socialblade.com/youtube/top/country/mc',
  'https://socialblade.com/youtube/top/country/mn',
  'https://socialblade.com/youtube/top/country/ms',
  'https://socialblade.com/youtube/top/country/ma',
  'https://socialblade.com/youtube/top/country/mz',
  'https://socialblade.com/youtube/top/country/mm',
  'https://socialblade.com/youtube/top/country/na',
  'https://socialblade.com/youtube/top/country/nu',
  'https://socialblade.com/youtube/top/country/np',
  'https://socialblade.com/youtube/top/country/an',
  'https://socialblade.com/youtube/top/country/nl',
  'https://socialblade.com/youtube/top/country/nv',
  'https://socialblade.com/youtube/top/country/nc',
  'https://socialblade.com/youtube/top/country/nz',
  'https://socialblade.com/youtube/top/country/ni',
  'https://socialblade.com/youtube/top/country/ne',
  'https://socialblade.com/youtube/top/country/ng',
  'https://socialblade.com/youtube/top/country/nw',
  'https://socialblade.com/youtube/top/country/nf',
  'https://socialblade.com/youtube/top/country/no',
  'https://socialblade.com/youtube/top/country/om',
  'https://socialblade.com/youtube/top/country/pk',
  'https://socialblade.com/youtube/top/country/pw',
  'https://socialblade.com/youtube/top/country/ps',
  'https://socialblade.com/youtube/top/country/pa',
  'https://socialblade.com/youtube/top/country/pg',
  'https://socialblade.com/youtube/top/country/py',
  'https://socialblade.com/youtube/top/country/pe',
  'https://socialblade.com/youtube/top/country/ph',
  'https://socialblade.com/youtube/top/country/po',
  'https://socialblade.com/youtube/top/country/pl',
  'https://socialblade.com/youtube/top/country/pt',
  'https://socialblade.com/youtube/top/country/pr',
  'https://socialblade.com/youtube/top/country/qa',
  'https://socialblade.com/youtube/top/country/me',
  'https://socialblade.com/youtube/top/country/rs',
  'https://socialblade.com/youtube/top/country/re',
  'https://socialblade.com/youtube/top/country/ro',
  'https://socialblade.com/youtube/top/country/ru',
  'https://socialblade.com/youtube/top/country/rw',
  'https://socialblade.com/youtube/top/country/nt',
  'https://socialblade.com/youtube/top/country/eu',
  'https://socialblade.com/youtube/top/country/he',
  'https://socialblade.com/youtube/top/country/kn',
  'https://socialblade.com/youtube/top/country/lc',
  'https://socialblade.com/youtube/top/country/mb',
  'https://socialblade.com/youtube/top/country/pm',
  'https://socialblade.com/youtube/top/country/vc',
  'https://socialblade.com/youtube/top/country/sp',
  'https://socialblade.com/youtube/top/country/so',
  'https://socialblade.com/youtube/top/country/as',
  'https://socialblade.com/youtube/top/country/sm',
  'https://socialblade.com/youtube/top/country/st',
  'https://socialblade.com/youtube/top/country/sa',
  'https://socialblade.com/youtube/top/country/sn',
  'https://socialblade.com/youtube/top/country/sc',
  'https://socialblade.com/youtube/top/country/sl',
  'https://socialblade.com/youtube/top/country/sg',
  'https://socialblade.com/youtube/top/country/sk',
  'https://socialblade.com/youtube/top/country/si',
  'https://socialblade.com/youtube/top/country/sb',
  'https://socialblade.com/youtube/top/country/oi',
  'https://socialblade.com/youtube/top/country/za',
  'https://socialblade.com/youtube/top/country/es',
  'https://socialblade.com/youtube/top/country/lk',
  'https://socialblade.com/youtube/top/country/sd',
  'https://socialblade.com/youtube/top/country/sr',
  'https://socialblade.com/youtube/top/country/sz',
  'https://socialblade.com/youtube/top/country/se',
  'https://socialblade.com/youtube/top/country/ch',
  'https://socialblade.com/youtube/top/country/sy',
  'https://socialblade.com/youtube/top/country/ta',
  'https://socialblade.com/youtube/top/country/tw',
  'https://socialblade.com/youtube/top/country/tj',
  'https://socialblade.com/youtube/top/country/tz',
  'https://socialblade.com/youtube/top/country/th',
  'https://socialblade.com/youtube/top/country/tg',
  'https://socialblade.com/youtube/top/country/tk',
  'https://socialblade.com/youtube/top/country/to',
  'https://socialblade.com/youtube/top/country/tt',
  'https://socialblade.com/youtube/top/country/tn',
  'https://socialblade.com/youtube/top/country/tr',
  'https://socialblade.com/youtube/top/country/tu',
  'https://socialblade.com/youtube/top/country/tc',
  'https://socialblade.com/youtube/top/country/tv',
  'https://socialblade.com/youtube/top/country/ug',
  'https://socialblade.com/youtube/top/country/ua',
  'https://socialblade.com/youtube/top/country/ae',
  'https://socialblade.com/youtube/top/country/gb',
  'https://socialblade.com/youtube/top/country/us',
  'https://socialblade.com/youtube/top/country/uy',
  'https://socialblade.com/youtube/top/country/uz',
  'https://socialblade.com/youtube/top/country/vu',
  'https://socialblade.com/youtube/top/country/vs',
  'https://socialblade.com/youtube/top/country/ve',
  'https://socialblade.com/youtube/top/country/vn',
  'https://socialblade.com/youtube/top/country/vb',
  'https://socialblade.com/youtube/top/country/va',
  'https://socialblade.com/youtube/top/country/wk',
  'https://socialblade.com/youtube/top/country/wf',
  'https://socialblade.com/youtube/top/country/ye',
  'https://socialblade.com/youtube/top/country/zr',
  'https://socialblade.com/youtube/top/country/zm',
  'https://socialblade.com/youtube/top/country/zw',
];

const pages = [
  'https://socialblade.com/youtube/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw/monthly'
];

const re = /[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9],[0-9]+/;

function extract(text) {
  text = text.split('\n');
  for (let line of text) {
    if (re.test(line)) {
      // console.log(line.slice(0, line.length - 4));
      const csv = safeEval(line.slice(0, line.length - 4));
      const rows = csv.split('\n');
      let table = '';
      if (rows[0].includes('Daily Subs')) {
        table = 'dailySubs';
      } else if (rows[0].includes('Total Subs')) {
        table = 'totalSubs';
      } else if (rows[0].includes('Daily Views')) {
        table = 'dailyViews';
      } else if (rows[0].includes('Total Views')) {
        table = 'totalViews';
      } else if (rows[0].includes('Average Views')) {
        table = 'averageViews';
      } else if (rows[0].includes('Monthly Views')) {
        table = 'monthlyViews';
      }
      for (let row of rows.slice(1, rows.length)) {
        if (!row) {
          continue;
	}
        const [date, value] = row.split(',');
        console.log(table, date, value);
      }
    }
  }
}

for (let page of pages) {
  fetch(page)
    .then(res => res.text())
    .then(extract)
}
